language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: eVZMmigLuLqjIRIB+SV1SapHzR0uuUVjU8o+3rSpgYl1f8m472MIbR0bQTU4v3MPBqHbE+qlL7Fpa4nu+7RUq6rUL6mzdJA2PNwoO6BqfPR8Nq5KMAeR86QFlakNG9SkMrKPd85yejHfQ/nG7uTrrG+2Xub6HTXq6VQZX7a08WonQJvssQgcrD1JwVfgD4cQY/oN+pHYOjLBbIy/xht4uPmXlPcI9Q0usOnACxo5SKKuD0xWzfDr4jOclfKDLOdxSMYq36Vx5JANyfZvySAY7ylwxq6ySzJ62X/Okxji/iZpvotfto0m6B62fMiLyZZ8ib0LnzMTGpkK/iuBnD8cHQlohx9XAuzIvIYa1aJwZ8Mgkw1vugEheZaPTKzZ/LF/3Pi1cD4e5ICbISAIhIhM/ny98sLpk2wU3GyLBtyl8RoLyuUGkmJcY7e2BVILRecMrcYdd9wfiA9Yod0Brl8mDmexIBV0HnoRN8TfnzCDtlc0TzVxTJ6Wxhoz8n5/O9wDZPlzFRqKQYJJAuBjQQYKKLYlWRiA7tSbBmHT3iRX0N1Ky3NXhO+l0TTEq1vpBmJl6GqBwqvN9s6gvyLVATJ4ECCAWc+h5DC8j9VToicFwrmU8/T4K0+5lSb0IXwtmKgL0KFOC3SjWvRLSkUi6bzyqMNTAQcHpYfN3pb+cxIC/44=
  app: stacktest8
