language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: khsKBBbAa17b+CHGz+hQsfjsYhkGW18c9U0TIeq/GOwYcbyhNJh8T0Jklsm3xM8n7rejr6s98GigGb4QoK3CQhZsTjFxzdafkDIhLhRPHExvxOMKQ6SEHfYWZvCedFjbveYGKsnwfPOziy7CvarFtrHFIUIjeUGlPdp6jrqm5KhfPQMWLDS43RgqKVjYOfChgmkjX44QKfUKc3zPrs95SzNsyCPiMAmf8usWxkD0YjrCe+meTq7/pCM7rSOqM3sT6tvpzBNekf2iqkbZ0v8/gkB8BxP8eH01DaD7WieVyZvz7jcm+32wGsBwY3FazhJxXW1TXezfbvXkLwbNjz1amNCTSQ5LIe3M/H/aYjsQS+0wS3haa8uBfAFu/04wbL2t97BLmQekDtpDpsLUliwiyzgHlCHtdLJ5kBE0d1RvwwDOaqVUQd+nE3L62CVTCclfW6ln5p4b6exZUnzonLM1xirz0CVAvUcY0EdX3ykZJq8b+sx6wNEpOlU4bocxHTLdspDpHvt5GinmvDeqZxYegdK39PWVCehdTelUprA1M1hAFTtZQXHzOG4EDOKC4yEd0vvFe1e/vNQ91KJ1peDfI0u1aLKtudcpwdXY7kx1uCvcSe3eyQeDRAau8XfirachMv0cGgonS6Bxzkj/X/lJc+3QN0kh4NGHY/z404M2Vtg=
  app: stacktest8
