language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: Qex4mHejgkSiCQnJUUaqP7jxoFo2rQRpUr/rerw7Q21FKF7TOk9wuxsDtDaKA5cIDeuNkNhX3EUp7VWU7DQxPrrtpnCPBYhYqTB54vTmYxNTq23ahUZ0hidqTlKPUSPOMXyzK+dxCc2LQSP2TUtYzzhFsr2VvBdwpMvzlkfgbvzo2iluVEMwOBYZrhB85f553GWR5wt1kCzcbFEJdnVNI1536AHFbNWwLstgngu3ZCBv1lQiEGjNk0amBb3IQzrykGCKsItNrNkRRfSKfgIvk97jL8rR5bCuA3z6r2ywfUSJtP206JaXKP95DY1GiS1pHkG8ZlYJMdN1wIQuOxDXSoEcydxfiDkDVYiWYpt2W0NSt9SfG8kkN8PAPJ4AHnWmub5IPy7OiLkHtbNjcsAiYLW6z/QlAu7xVpXivtecNpO+yxND8Oq60vwdFDF1p+HoSRbm69+3F7ibMcO2F1xFtlD6Br1bv2pwzKcmcJoASiSvvjrIsunhCxjn4rEVm2ifT9vjgkoEYfhZlbIVfl4yC282D+Ri/eKN05kwxCIxRsoaaHU9D7zIyjl6g46Y5+v9ugL13yIHoGOd/F4bdK+PEMEV5TxHl0Ek8U+gO+FXhxhg20rJ5m1aUBD9kdktMDq7WAFJA+2oqxSzWSfwFdDybf6RCXeUCLEg0YnYqYJsE70=
  app: stacktest8
