language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: m9IHN1s2dSwLEWws6qGwuBWKyB3UHM/43B7HNGoFIG9LoamOvBq2Ld35F8H/EuS6IFMns9+WQkrhaIkyM0AFA3VXUbATmkfxPHOJWEyknMA+O+EB3tiF4COVyk86qltzOQkKTDkYMVfmgnu6B9cvl6C9ptBn5H4tw+t0mQwJRXRwfpb89/9Lhs0xiW0U1GeVYb3I4ePKF3bXd5f1uaXxNeogjAmcbDrgCx6sS+4OduA2z/y9B9BgDN6qA06PmzVxFUSF0ks+Ftqbk3SEqednzuVLE7fFqqoxeflp0V1TRmcumiWtq/VaMCd4Ma9+8rJ7sJUdhmqXgwuNRvyyij9Dn8jVmVt8JMMQiPQk0NWBFRzFbjuaCsfeIs8m1GA2SCd+TfROcwj2z5FcPqS5yABl7S8cpBCFdXBsRWHGtUGfsdpWGEQLD2+WNS1tTP+b8Ff6l7MAhB94D0UQWh+q36t0rJK8UzC1RjY7ZqNF8fOYr1GSGfaE6g3KzKftAxkC0y/Ky1k+hfl3gEl0bZhXvdTIQLRlzPEAynWcfppUXx8HbpODiLzPKyyeoJsde7qj4sJXxdGWIIAuFHSf83sHq1yiU+WU8Tu5OMyafKboJgnzde59DXkEbPN78qGigA3xIHIcEuuOCjWawFclLRGaxAbQA0F/DgOxt1lZhFu0LCRcx1Y=
  app: stacktest8
