language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: dTgovvc7R9hypzsUoEwOb6UK+NDXNzg62AMuwbVTu/RQN/89rQsWdomQ4HY0gJTLhOVqUpLFRo0s6PiJsobyAWRVRWCieb9U7u5hLaPQCI2nyMkH/xXtLLISvBU8CboT2pD4lDPdCoavOPx+fK8+lLJI19Fl/6mRifVR3tMH9uuQkSjHErCYQZYIF55nafrOkYlBBLDoZb3Rg+5VXd+wO//EHr45rAbsXnHTCNaf5YUiByG/eC5GYybU7morWlIL2IFCx1f94RFqw52mcmWnRkOjPIPkLTVWg2rq2eb3FKovsvhJu6dKhyhss7Cu012kqNaaUif2JtzFx69SrjTMx8YAIdjGnPolvpVKwmepDMjKY6U5XbTztu13aWu7lc4NEA/O2ydolWJlkITopFttexvr7yDqY3Xa6R/X8RzubiJYz1imC96+waGeq2xkubvoDq9Uj3exE+JEDNgXxTsZoYzsLfEXKqqw3GD2SNU/smYhkBUSjKy5xQjXgiwiePLJIcDjerWnZ02bvZoUkT0OovQncdWvq42TjUZm6ECiHVLgohfYabmwvP6I/jjRv4c8HilSf/0NqnW5IZG+FWanjlco9HTkJ50Jcv4aU0ruDYqheloJgjJg4BK1aYu72YEUGBNZLN9VrdjIj6piuRa1UvTo0gOe6p2bdopQRbMJPJk=
  app: stacktest8
  on:
    repo: glowlex/2016_2_StackDouble
