language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: TlIQV0GTtkHzm0V/I1CvNtSn4lPhHWbRe6lWKytFuERMX+psF2MDdMHhe+BGL6EbYDrZ0OpdHF6osm6iOeEI9d3WBepX8q0DF39Flnlq+k7E2Dq6YjTdJ1/zgSAzUznIElLncCEOulJRwQk8e8vT2YAPFOMKmIo4KybOYLKcg11AueFWKk52SGr5qkz//D6uyFL/ZfFdodq3ffkb0JLCwK2I0wBa4lc/ayFO1roEBzYq7bxAlcA8OzhBMMlfS2ntaqmLSXVJq35H0VH36BkqUG5TYRzTsxx+7yLShTYasZwgE6/gK3/j6apMJv0LY/wV2pdZa3zjzZJVumHM6AWMHSKfj6zi0KTCQfOgQzkwLK6BlcIoD7TgXVEFO6ITvQS5FA36SFHpByVwsQAi871XubuQ7FRCdHMghZzz6UjG2i2Hjbxm/rwcYI5ZcK1WQrVqENlUpWofi1nxbWAZyu653F+tDOOLXV3Sbgjpq2WpEgm22QegyJrIvweFb0FxwYu8QkNNVuIsQAuqI3pw570o6dGPGHt6gQmL2+fMxd3PEZhiWgKYlUriWb+gGi89pYq3I+eSf8uJBgwdYrJM2yap1WANDyOyaXG1o0E9ie/k1ZuxeGRQaY72HV8aob/wHjQ1oTczA7SuQQdWkoq9vUzVNqpOFAc9PHnKZgKndqz4n2k=
  app: stacktest8
  on:
    repo: glowlex/2016_2_StackDouble
    branch: master
