language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: CRA1obT4I0Vpx/SzavTzpUKe34rM2VrKr0Pa+v7nZPB0R+KLyhqYsN+g96mUCzPuVwi2siKqToaeeVCF1tkFG5e7AV5Ph4nFpmZ0/Ovp54KfE8jmPu9dErIW1wyN+neQeVGwCsFbkLCE+cK6/OOhAFsQOSy+jY1tPPUn0v6I4xMKvooyOLjOersgvm/qMIq2PcPCEOjkzLFQpA+w3J7CkfrQVrRwLoA8EoVmY8PiCJo4EStiwtxwEy2310XuZteoWfenBjORU+np2dkZ2HGqa9NtUpi7XqBTga2G+eoBS9xMmV01bVjquXSy+zzVlTUZH+ITkG8axMXKuQWHnMHeTwNtxvgcVpYuFZSkmHDz21Az5i6u8dXhi7MRqEVz5sgCrf0+g1GEV9FoxgKRdcMdFQsWW6Xs+xAk2C4CL4t3TrzaREZX/MZGpgTUfmmle89YzVvkfZ6D4H9XnAjSo54P7OtWYRFPgpJAlOhymlLAAjSWCclxjpGek7Al1/Tvfc2LEemgTlmS4lPUwc6z1pr+FsFKGQEd+7Eruq15K/tE2YSIt6uYoX59cSQ5xBmFZSRjYpGBkMJlKUCq8PXi4ZAl34O4ON0sHOYoABjzXUhhgmK85KH/lOazKUUiYM9/XigbuhzFILlIdulw40v2xFJEt90bni9gVUkasCZ9RnkTgSg=
  app: stacktest8
  on:
    repo: glowlex/2016_2_StackDouble
