language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: W2kwchg4da/UYlY7xP7HreQZfIq13olojOKEar/II1EMEcxozGlNKVkjSYKY9zleNF/XHbvjrOiHJvTiBx1YOfvl004IzJGHGE8ZyozKJK2h40HqPahAjNkxoq0fP//2Snp/OupzIDZB0Tb/esF2twlZtOMY93cvjYauI/cCXo0HJY/5H8aaaVQCIPtjuQcjeRf+VfVfPmQwCXEga6khy+KeWBfSH4LXLpZRB2gpo7fOyWVHBHu4tRrXdw3ISKXon4rbZaX5azOStAJMMOS89sNUeWoRhT44x6UmeqGb4wTgehFd8vAh4LhFhvTN7VVbZiamFBiN8+FdzLXTvz7yi5diG4Sn5Dnf1QY/f31FuBuXcfcpeSjlwsTaNiYKSrfa1F1hVvNiDkwsQ0e/0Pak3m/xDAXF7Iuk/C1IWn3De8RT/IaZ9JxEi8k++219twVp0wK199HaW/lSdEodlqkzyFxMkegByxbwS9gWPgzZrhv9teShVJbr5/qImjtpTatBis03EP14yC3Y1bspHJ81l3bzDfPGaHr1NvgFqFBjabdDS0+KU3mwNa3JHHkQjXcv1M/dvnH+fV7a2WjjKUq37UJR9Kr+vANIv6szd1q3DwWoBywaOGn6MzQeZ8Vy0UVbg9CK2Uhtz7mIJktPdVof3wur3LJs8Jjk1nsAuVlO1TI=
  app: stacktest8
