language: node_js
node_js:
- 6
deploy:
  provider: heroku
  api_key:
    secure: m057cMROzJHRqw6ansTDrXfbZSznUf7KDDFnS/SftxnevvVtyhxLx1LSLHYeq3mNHBMlS1cA+tsLDemWPCK73zgRHBTRkW2elO7NdJ9bvtyqitggTob9wpd827x+TlLG9z6KqQhG0iVp8QGBUV/kRS0bV39Jx9IZcB7oNPiNyeXGXWdaCcruedc5fDZ6EuLLaXyx1GOpofl5haOsImZMtCttMvFAfeNc5KYVNqtJsCTe6EavYL/iOE5NFswZBoOvt/7ha42WYFWgdE4l0+iQ7P4coeaVLdCu7g4cfKAlvzApWeklEbilB1fC2xNGL1/Zew0hLN6ILGHFpngTV+qh3K8mRThV6E3hBYhIcGtPPmY+OGng8IUNMS8nmQxW3Uj+y13VP/jqOuki1fBNCMfr7lOYPw22XbqIvIlw6Mb6vbhOCZPtU0j4p7b89G0SdVFfmEYiH0/5eEDIxbhvyMY4tyWaUHWOAwXVjgsKTs/3pagSl3zOYWXpAsV0Ozss9mbZH27AQcHrKkhmofxdwaCj5uH6DzGOgbhVas9zuiZpKtgBZMxSbS8QTo+8novZG4fQzGrBxo6AFLrYvYm+v04RApelt38/Pbu8rEk5fbK7hH0PT9ddl/Kedr5j5VXxO5kjiDxBFEv9lOgheJWCGRWMPDpbsXOXEjUz9iCetTT8zWY=
  app: stacktest8
